### ISSUE TITLE
[autosavemoney]  一定金額を入れるか、一定金額を残すかを選べるようにしてほしい

### ISSUE THREAD

**Issue by kajikum** [chicori/TOS-Addon#2]
別に無くても良いのですが、現在の実装だと所持金が100,000シルバー残るようになっています。
それ以外に、一定金額を自動で設定するような機能も欲しいと思いました。  
ニーズがそこまでないと思うので、気が向いたらぐらいでもいいです。

**Comment by chicori** [comment]
v1.0.1で対応できた・・・かな？外部設定の処理これであってるかちょと不安。

**Comment by kajikum** [comment]
怪しいところですけど、個人的には欲しい機能になっていたので、閉じちゃいますねw

ありがとうございます！
