### ISSUE TITLE
アラーム(仮)アドオンのフレーム

### ISSUE THREAD

**Issue by torahamu** [chicori/TOS-Addon#3]
zipの中にluaファイルとxmlファイル入ってます。
ちょこちょこ処理も書いちゃいましたが

![default](https://cloud.githubusercontent.com/assets/23138318/23216673/23090a88-f95a-11e6-93a7-1360a33539b6.png)

[alarm.zip](https://github.com/chicori/TOS-Addon/files/793831/alarm.zip)

**Comment by chicori** [comment]
すーぱーありがとうと言わざるを得ない。
