### ISSUE TITLE
English version done

### ISSUE THREAD

**Issue by bsides** [chicori/TOS-Addon#4]
Hi @chicori, I made an english translation of your addon "Alarm". Could you publish it? I've done the same to another addon (Barrack Itemlist, by another user), that's why there's an english version in the manager right now. I'm sure there will be a better way to make this, I'm just using a shortcut.

Thank you for you addons by the way :)

EDIT: the repo is [here](https://github.com/bsides/TOS-Addon)

**Comment by chicori** [comment]
Hi @bsides bsides, thank you for your message.
I am thankful for the suggestion, but I have no skills to register other than "AddonManagerJP".
Could you please publish the "alarm"?(p･_･q)

**Comment by chicori** [comment]
Hi @bsides , thank you for your message.
I am thankful for the suggestion, but I have no skills to register other than "AddonManagerJP".
Could you please publish the "alarm"?(p･_･q)

**Comment by bsides** [comment]
@chicori it's in the "JTOS Addon Manager" that you could publish, but I could also publish in my name. I just want to check with you first before doing it because I'm not the author. Is that ok then?

**Comment by chicori** [comment]
sure thing.That would be great.
thank you.

**Comment by bsides** [comment]
@chicori I am trying a different approach. Instead of having 2 addons with the same name, one in japanese and other in english, I am modifying your addon to have both languages and be configurable by the user. For the japanese user it will not change anything, but for the english user he can change the language by using the slash command `/al en`. What do you think? This way you can just release it like you released before and do not worry with the rest.

EDIT: I created a pull request with the changes mentioned above #5

**Comment by chicori** [comment]
thank you.
but i'm not playing game.
